<?php

/**
 * @file
 * Primary module hooks for MET Push module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function met_push_theme(): array {
  return [
    'met_push' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for push notification templates.
 *
 * Default template: met-push.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the push notification information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_met_push(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function met_push_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish push notifications.
      $storage = \Drupal::entityTypeManager()->getStorage('met_push');
      $met_push_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($met_push_ids) as $met_push) {
        $met_push->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize push notifications.
      $storage = \Drupal::entityTypeManager()->getStorage('met_push');
      $met_push_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($met_push_ids) as $met_push) {
        $met_push->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function met_push_user_predelete(UserInterface $account): void {
  // Delete push notifications that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('met_push');
  $met_push_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($met_push_ids)
  );
}
