<?php

/**
 * @file
 * Primary module hooks for MET Feel Earthquake module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\met_feel_earthquake\METFeelEarthquakeInterface;


/**
 * Implements hook_theme().
 */
function met_feel_earthquake_theme(): array {
  return [
    'met_feel_earthquake' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for feel earthquake templates.
 *
 * Default template: met-feel-earthquake.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the feel earthquake information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_met_feel_earthquake(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function met_feel_earthquake_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish feel earthquakes.
      $storage = \Drupal::entityTypeManager()->getStorage('met_feel_earthquake');
      $met_feel_earthquake_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($met_feel_earthquake_ids) as $met_feel_earthquake) {
        $met_feel_earthquake->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize feel earthquakes.
      $storage = \Drupal::entityTypeManager()->getStorage('met_feel_earthquake');
      $met_feel_earthquake_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($met_feel_earthquake_ids) as $met_feel_earthquake) {
        $met_feel_earthquake->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function met_feel_earthquake_user_predelete(UserInterface $account): void {
  // Delete feel earthquakes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('met_feel_earthquake');
  $met_feel_earthquake_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($met_feel_earthquake_ids)
  );
}


/**
 * Implements hook_ENTITY_TYPE_insert() for node.
 */
function met_feel_earthquake_insert(METFeelEarthquakeInterface $fe): void {




}
