name: Composer Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_cache:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        id: cache-keys
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

  coding_standards:
    needs: setup_cache
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding Standards Check
        run: composer coding_standards

  php_compatibility:
    needs: setup_cache
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP Compatibility Check
        run: composer php_compatibility

  drupal_check:
    needs: setup_cache
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Drupal Check
        run: composer drupal_check
