name: Automated Tests

on:
  - pull_request

env:
  LANDO_VERSION: v3.21.0

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Grab latest Lando CLI
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${LANDO_VERSION}"
          sudo chmod +x /usr/local/bin/lando

      # This is optional.
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Fix the latest lando issue
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # the full version of `docker-compose` command

      # Setup Lando
      - run: lando setup

      # Boot Lando and set up Drupal
      - run: lando start
      - run: lando composer install
      - run: lando composer require --dev drupal/core-dev
      - run: lando ssh --command "cp modules/custom/met_api/modules/met_api_test/assets/phpunit.xml core/phpunit.xml"
      - run: lando ssh --command "cp core/.env.example .env"

      # Install Drupal
      - run: lando drush si -y --db-url=mysql://drupal10:drupal10@database:3306/drupal10
      - run: lando drush cset system.site uuid "5bb79423-cfb5-4dd1-98fc-1efb2a54c645" -y
      - run: lando drush entity:delete shortcut_set
      - run: lando drush en paragraphs met_warning met_tk -y
      - run: lando drush cim --source=config/site -y

      # Set private file path
      - run: lando ssh --command 'mkdir /var/www/private'
      - run: lando ssh --command 'chmod 744 /app/sites/default/settings.php'
      - run: lando ssh --command 'ls -la /app/sites/default/'
      - run: lando ssh --command 'echo \$settings[\"file_private_path\"] = \"/var/www/private\"\; >> /app/sites/default/settings.php'
      - run: lando drush cr

      # Enable the test module
      - run: lando drush en met_api_test -y

      # Copy test file to private directory
      - run: lando ssh --command 'cp -R modules/custom/met_api/modules/met_api_test/assets/. /var/www/private/'

      # This will run tests. If any tests fail, it will fail here.
      - name: Run Newman test
        run: lando newman run modules/custom/met_api/modules/met_api_test/assets/api_test.postman_collection.json -e modules/custom/met_api/modules/met_api_test/assets/local.postman_environment.json

      - name: Run unit test
        run: lando composer test-niwa-module
